@api = http://localhost:4000

GET {{api}}/videos

###
GET {{api}}/videos/63d85c2139e72a8412837906

###
POST {{api}}/videos
Content-Type: application/json

{   
    "url": "https://www.youtube.com/watch?v=_RZ-T6TxP7w&t=114s&ab_channel=Fazt",
    "title": "pruebiña", 
    "description": "descripcion de prueba"
}
###
PUT {{api}}/videos/63d1ea47fdbaa04568da7736
Content-Type: application/json

{
    "title":"se dice prueba br inepto"
}

###
DELETE  {{api}/videos/63d85c2139e72a8412837906}